name: kyma-project.io/module/template-operator
channel: regular
version: 1.0.0
manifest: template-operator.yaml
security: sec-scanners-config.yaml
defaultCR: ./config/samples/default-sample-cr.yaml
annotations:
  operator.kyma-project.io/doc-url: https://kyma-project.io
