name: kyma-project.io/module/template-operator
channel: regular
version: 1.0.1
manifest: https://github.com/kyma-project/template-operator/releases/download/1.0.1/template-operator.yaml
security: sec-scanners-config.yaml
repository: https://github.com/kyma-project/template-operator
documentation: https://github.com/kyma-project/template-operator/blob/main/README.md
defaultCR: https://github.com/kyma-project/template-operator/releases/download/1.0.1/default-sample-cr.yaml
icons:
  - name: module-icon
    link: https://github.com/kyma-project/template-operator/blob/main/docs/assets/logo.png
resources:
  - name: raw-manifest
    link: https://github.com/kyma-project/template-operator/releases/download/1.0.1/template-operator.yaml
manager:
  name: template-operator-controller-manager
  namespace: template-operator-system
  group: apps
  version: v1
  kind: Deployment
