module-name: template-operator
kind: kyma
checkmarx-one:
  preset: go-default
  exclude:
    - "**/test/**"
    - "**/*_test.go"
bdba:
  - europe-docker.pkg.dev/kyma-project/prod/template-operator:1.0.3
mend:
  language: golang-mod
  exclude:
    - "**/test/**"
    - "**/*_test.go"
