module-name: template-operator
rc-tag: 1.0.1
dev-branch: main
kind: kyma
checkmarxOne:
  checkmarx_preset: golang
protecode:
  - europe-docker.pkg.dev/kyma-project/prod/template-operator:1.0.1
whitesource:
  language: golang-mod
  subprojects: false
  exclude:
    - "**/test/**"
    - "**/*_test.go"
