module-name: template-operator
rc-tag: 0.1.2
dev-branch: main
protecode:
  - europe-docker.pkg.dev/kyma-project/prod/template-operator:0.1.2
whitesource:
  language: golang-mod
  subprojects: false
  exclude:
    - "**/test/**"
    - "**/*_test.go"
