name: Build Image

permissions:
  contents: read # This is required for actions/checkout

on:
  push:
    branches:
      - main
  workflow_call:
    inputs:
      tag:
        description: 'Additional tag for built image'
        required: false
        type: string
        default: ""
  pull_request_target:
    types: [ opened, edited, synchronize, reopened, ready_for_review ]

jobs:
  get-custom-tags:
    runs-on: ubuntu-latest
    outputs:
      tags: ${{ steps.get_custom_tags.outputs.tags }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2
      - name: Get tags
        id: get_custom_tags
        run: |
          tags=""
          if [[ "${{ github.event_name }}" == "push" ]]; then
            tags="latest"
          elif [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            tags="${{ inputs.tag }}"
          elif [[ "${{ github.event_name }}" == "pull_request_target" ]]; then
            tags="${{ github.event.pull_request.head.sha }}"
          fi
          echo "Using custom tags: '$tags'"
          echo "tags=$tags" >> $GITHUB_OUTPUT

  who-am-i:
    runs-on: ubuntu-latest
    steps:
      - name: Show my association
        run: |
          echo "Author association: ${{ github.event.pull_request.author_association }}"
      - name: Check if OWNER
        if: ${{ github.event.pull_request.author_association == 'OWNER' }}
        run: echo "You are an OWNER"
      - name: Check if COLLABORATOR
        if: ${{ github.event.pull_request.author_association == 'COLLABORATOR' }}
        run: echo "You are a COLLABORATOR"
      - name: Otherwise
        if: ${{ github.event.pull_request.author_association != 'OWNER' && github.event.pull_request.author_association != 'COLLABORATOR' }}
        run: echo "You are neither OWNER nor COLLABORATOR"

  build-image:
    runs-on: ubuntu-latest
    needs: [get-custom-tags, who-am-i]
    environment: image-build
    permissions:
      id-token: write # This is required for requesting the JWT token
    uses: kyma-project/test-infra/.github/workflows/image-builder.yml@main
    with:
      name: template-operator
      dockerfile: Dockerfile
      context: .
      # tags are additional tags that will be added to the image on top of the default ones
      # default tags are documented here: https://github.com/kyma-project/test-infra/tree/main/cmd/image-builder#default-tags
      tags: ${{ needs.get-custom-tags.outputs.tags }}
