name: build image

on:
  push:
    branches:
      - main
  pull_request_target:
    types: [opened, edited, synchronize, reopened, ready_for_review]


permissions:
  id-token: write # This is required for requesting the JWT token
  contents: read # This is required for actions/checkout

jobs:
  build-web-image:
    uses: kyma-project/test-infra/.github/workflows/image-builder.yml@main # Usage: kyma-project/test-infra/.github/workflows/image-builder.yml@main
    with:
      name: template-operator
      dockerfile: Dockerfile
      context: .
      export-tags: true
      tags: latest