name: Integration Tests

on:
  pull_request:
    branches: ["main"]

jobs:
  integration-tests:
    name: "Run integration tests"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Template Operator
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
      - name: Run integration tests
        run: make test