name: Integration Tests

permissions: { }

on:
  pull_request:
    branches: ["main"]

jobs:
  integration-tests:
    name: "Run integration tests"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Template Operator
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Set up Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7
        with:
          go-version-file: 'go.mod'
      - name: Run integration tests
        run: make test