name: Assets upload

on:
  create:
    tags:
      - 'v?[0-9]+.[0-9]+.[0-9]+(?:-.*)?'

jobs:
  upload-assets:
    name: "Upload assets"
    runs-on: ubuntu-latest
    env:
      PULL_BASE_REF: ${{  github.ref_name }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout template operator
        uses: actions/checkout@v4
      - name: Run upload assets script
        run: ./scripts/release/upload_assets.sh