apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Adds namespace to all resources.
namespace: template-operator-system

# Value of this field is prepended to the
# names of all resources, e.g. a deployment named
# "wordpress" becomes "alices-wordpress".
# Note that it should also match with the prefix (text before '-') of the namespace
# field above.
namePrefix: template-operator-

resources:
  - ../../base
  - ../../manager/deployment

patches:
  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --final-state=Ready
    target:
      kind: Deployment
  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --final-deletion-state=Deleting
    target:
      kind: Deployment